platform :ios, '10.0'

target 'Routefire' do
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'LyftSDK'
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'SnapKit'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'IQKeyboardManagerSwift'
  pod 'TouchVisualizer'
end
