platform :ios, '10.0'
use_frameworks!

target 'Routefire' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'IQKeyboardManagerSwift'
  pod 'TouchVisualizer'
end
